version: "3.8"

services:
  postgres:
    container_name: ts-api
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: ts-api
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
